### ISSUE TITLE
[NE] Add support for HTTP errors

### ISSUE THREAD

**Issue by pblcc** [Tony1324/tonyzhang.net#1]
Hi. Tony, right?
You see, I found you on Twitter and I noticed you because you mention that you are in the eighth grade. I'm a "ninth" (here it doesn't work like that) and when I see someone our age I like to investigate a little more.
Exploring your Github I came across this website, which is beautiful but I just wanted to mention that **it has no error handling for [HTTP errors](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)**.
GitHub allows the option to modify the page for these errors by adding a document called `error-code.html` at the route of the repo. For example `404.html`.
Maybe you want to leave it like that. but **if you want to modify the style of these errors you may be interested**.
I was going to send you an email to comment on it, and thus not have to open an issue. But I have not found your email and you do not have the twitter md open either. That's why I'm labelling this as *NE*
I would have done the pr myself just in case, but I have no idea of ​​web programming.
![Screenshot from 2021-01-31 20-23-28](https://user-images.githubusercontent.com/63709477/106395361-35304480-6402-11eb-9a93-0ea6ffa04ff8.png)
##### Good luck from Spain 🇪🇸!

**Comment by Tony1324** [comment]
Hello! yup I'm Tony, 
thanks for telling me that I could do that with GitHub pages

**Comment by pblcc** [comment]
no worries. Good luck.

**closed**
